import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

import ksyusha from "../assets/ksyusha.jpeg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Julia's blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex justify-center bg-pink-100 m-30 p-30 h-screen">
        <Link href={`/posts`} className="block">
          <Image
            alt="Ksyusha"
            src={ksyusha}
            width={300}
            height={300}
            style={{
              maxWidth: "100%",
              height: "auto",
            }}
            className="p-10"
          />
        </Link>
      </main>
    </>
  );
}
